name: build

on:
  push:
    branches: [master]

jobs:
  generate_results:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mtiller/book-builder-image:v0.1.1
    steps:
      - name: Mark checkout directory as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Restore DVC Cache
        id: dvc-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            .dvc/cache
          key: dvc-cache-key
      - name: Make PDFs
        run: make env pdfs
      - name: Upload Executables
        uses: actions/upload-artifact@v3
        with:
          name: exes.tar.gz
          path: text/results/exes.tar.gz
      - name: Save DVC Cache
        id: dvc-cache-save
        uses: actions/cache/save@v3
        with:
          path: |
            .dvc/cache
          key: dvc-cache-key
